# Generated by Django 6.0.3 on 2026-03-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время фиксации взаимодействия.', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('viewed', 'Просмотр'), ('rated', 'Оценка'), ('liked', 'Лайк'), ('purchased', 'Покупка')], help_text='Определяет семантику ребра и вес при построении графа.', max_length=20, verbose_name='Тип взаимодействия'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='item',
            field=models.ForeignKey(help_text='Узел элемента в двудольном графе.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommendations.item', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.FloatField(blank=True, help_text='Для типа «Оценка»: значение по шкале (часто 1–5); для остальных типов не обязательна.', null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(help_text='Узел пользователя в двудольном графе.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommendations.recommendationuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(help_text='Категория: movie, book и т.д.; в графе узел вида i_{id}.', max_length=50, verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Отображаемое имя элемента (фильм, книга и т.п.).', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recommendationuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Автоматически при создании записи.', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='recommendationuser',
            name='username',
            field=models.CharField(help_text='Уникальный логин; в графе узел вида u_{id}.', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
